name = "weather-dashboard"
main = "_worker.js"
compatibility_date = "2025-09-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "SKI_DATA"
id = "88494e71b9134fcb84e1af2d16ffd1f7"

[vars]
VAPID_SUBJECT = "mailto:west.wong@westech.com.hk"

[triggers]
crons = ["*/30 * * * *"]
